# Generated by Django 5.2.1 on 2025-06-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primitiv', '0002_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
